development/scite: Updated for version 5.6.1.

diff --git a/development/scite/scite.SlackBuild b/development/scite/scite.SlackBuild
--- a/development/scite/scite.SlackBuild
+++ b/development/scite/scite.SlackBuild
@@ -30,7 +30,7 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=scite
-VERSION=${VERSION:-5.5.8}
+VERSION=${VERSION:-5.6.1}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -46,6 +46,11 @@ fi
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
+fi
+
+if [ -n "${TRANSLATION}" ] && [ ! -e ${CWD}/locale.${TRANSLATION}.properties ]; then
+  echo "Translation file not found for language \"${TRANSLATION}\" in the SlackBuild's directory"
+  exit 1
 fi
 
 TMP=${TMP:-/tmp/SBo}
