development/python3-numpy-legacy: Updated for version 1.26.3
Signed-off-by: Christoph Willing <chris.willing@linux.com>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/development/python3-numpy-legacy/python3-numpy-legacy.SlackBuild b/development/python3-numpy-legacy/python3-numpy-legacy.SlackBuild
--- a/development/python3-numpy-legacy/python3-numpy-legacy.SlackBuild
+++ b/development/python3-numpy-legacy/python3-numpy-legacy.SlackBuild
@@ -2,7 +2,7 @@
 
 # Slackware build script for python3-numpy-legacy
 
-# Copyright 2015-2023 Christoph Willing  Brisbane, Australia
+# Copyright 2015-2026 Christoph Willing  Sydney, Australia
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -29,7 +29,7 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=python3-numpy-legacy
 SRCNAM=numpy
-VERSION=${VERSION:-1.24.4}
+VERSION=${VERSION:-1.26.3}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -56,10 +56,23 @@ TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
+PYVER=${PYVER:-$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')}
+# For newer python3-packaging-opt
+export PYTHONPATH=/opt/python$PYVER/site-packages
+which python$PYVER 2>/dev/null 1>/dev/null
+[ "$?" = "0" ] || {
+  echo "Can't find python$PYVER. Exiting now ..."
+  exit 1
+}
+
+PYVER=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')
+export PYTHONPATH="/opt/python$PYVER/site-packages:/opt/cython/python$PYVER/site-packages"
+export PATH="/opt/cython/bin:$PATH"
+
 set -e
 
 rm -rf $PKG
-mkdir -p $TMP $PKG/opt/$PRGNAM $OUTPUT
+mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $SRCNAM-$VERSION
 tar xf $CWD/$SRCNAM-$VERSION.tar.gz
@@ -114,14 +127,38 @@ case "$DEBUG" in
 esac
 
 if [ ! "$DEBUG" ]; then
-  NPY_RELAXED_STRIDES_CHECKING=${NPY_RSC:-1} python3 setup.py install --install-platlib usr/lib${LIBDIRSUFFIX} --root $PKG/opt/$PRGNAM
+  NPY_RELAXED_STRIDES_CHECKING=${NPY_RSC:-1} python$PYVER -m build --wheel --no-isolation -Csetup-args="-Dallow-noblas=true"
+  python$PYVER -m installer -d "$PKG" dist/*.whl
 
   find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 else
-  NPY_RELAXED_STRIDES_CHECKING=${NPY_RSC:-1} python3 setup.py build --debug
-  python3 setup.py install --install-platlib usr/lib${LIBDIRSUFFIX} --root $PKG/opt/$PRGNAM
+  #NPY_RELAXED_STRIDES_CHECKING=${NPY_RSC:-1} python$PYVER setup.py build --debug
+  #python$PYVER setup.py install --root $PKG
+  echo "debug here"
 fi
+
+# Move libs to $PKG/opt
+# (trying to avoid clash with regular python3-numpy)
+#
+if [ "$PKG/usr/" != "/usr/" ]; then
+  mkdir -p $PKG/opt
+  mv $PKG/usr/lib*/python$PYVER $PKG/opt/
+  rmdir $PKG/usr/lib*
+else
+  echo "ERROR: \$PKG is not set! We don't want to move the real /usr/lib*/python$PYVER"
+  exit 1
+fi
+
+mkdir -p $PKG/usr/include
+cd $PKG/usr/include
+  # Location varies according to VERSION in 15.0 & -current
+  if [ -x /usr/bin/gcc-11.* ]; then
+    ln -s $(ls -d /opt/python$PYVER/site-packages)/numpy/core/include/numpy
+  else
+    ln -s $(ls -d /opt/python$PYVER/site-packages)/numpy/_core/include/numpy
+  fi
+cd -
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a CITATION.bib INSTALL.rst LICENSE.txt README.md THANKS.txt \
