network/sfeed: update to 2.4
Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/network/sfeed/sfeed.SlackBuild b/network/sfeed/sfeed.SlackBuild
--- a/network/sfeed/sfeed.SlackBuild
+++ b/network/sfeed/sfeed.SlackBuild
@@ -26,7 +26,7 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=sfeed
-VERSION=${VERSION:-2.3}
+VERSION=${VERSION:-2.4}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}		
 PKGTYPE=${PKGTYPE:-tgz}
@@ -77,7 +77,15 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-make
+
+SFEED_THEME=${SFEED_THEME:-mono}
+
+if [ ! -f "$CWD/themes/$SFEED_THEME.h" ] && [ ! -f "$TMP/$PRGNAM-$VERSION/themes/$SFEED_THEME.h" ]; then
+  echo "Invalid SFEED_THEME='$SFEED_THEME' (expected one of: mono mono_highlight newsboat templeos)"
+  exit 1
+fi
+
+make SFEED_THEME="$SFEED_THEME" CFLAGS="$SLKCFLAGS"
 make install PREFIX=/usr MANPREFIX=/usr/man DOCPREFIX=/usr/doc/sfeed-$VERSION DESTDIR=$PKG
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
