system/wine-staging: Updated for version 9.6.

diff --git a/system/wine-staging/wine-staging.SlackBuild b/system/wine-staging/wine-staging.SlackBuild
--- a/system/wine-staging/wine-staging.SlackBuild
+++ b/system/wine-staging/wine-staging.SlackBuild
@@ -33,9 +33,10 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=wine-staging
-VERSION=${VERSION:-9.5}
-WINEVERSION=${WINEVERSION:-9.5}
-STAGINGVERSION=$WINEVERSION
+VERSION=${VERSION:-9.6}
+WINEVERSION=$VERSION
+STAGINGVERSION=$VERSION
+ARCHS="i386,x86_64"
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -87,6 +88,15 @@ case "$ARCH" in
   ;;
 esac
 
+MULTILIB=${MULTILIB@L}
+if [[ "$ARCH" != "x86_64" && "$MULTILIB" = "yes" ]]; then
+  echo "Cannot build for multilib on non-64bit systems."
+  exit 1
+else
+  ARCHS="x86_64"
+  WINE32="yes"
+fi
+
 set -e
 
 rm -rf $PKG
@@ -115,8 +125,6 @@ find -L . \
 
 # Fix for flex.
 patch -p1 < $CWD/flex.patch
-# WriteCopy Fix.
-patch -p1 < $CWD/writecopy.patch
 # Fix path of opencl headers.
 sed 's|OpenCL/opencl.h|CL/opencl.h|g' -i configure*
 
@@ -135,7 +143,7 @@ if [ "$WINE64" = "yes" ]; then
     --sysconfdir=/etc \
     --mandir=/usr/man \
     --enable-win64 \
-    --enable-archs="i386,x86_64" \
+    --enable-archs=$ARCHS \
     --with-x \
     --with-gnutls \
     --${do_opengl}-opengl \
@@ -144,7 +152,7 @@ if [ "$WINE64" = "yes" ]; then
     --disable-tests \
     --build=$BUILD_ARCH
   make depend
-  make
+  make -j24
   make install DESTDIR=$PKG
   cd ..
 fi
@@ -172,7 +180,7 @@ if [ "$WINE32" = "yes" ]; then
     --disable-tests \
     --build=$BUILD_ARCH
   make depend
-  make
+  make -j24
   make install DESTDIR=$PKG
   cd ..
 fi
