misc/html2ps: Fix runtime bug.
Signed-off-by: B. Watson <urchlay@slackware.uk>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/misc/html2ps/html2ps.SlackBuild b/misc/html2ps/html2ps.SlackBuild
--- a/misc/html2ps/html2ps.SlackBuild
+++ b/misc/html2ps/html2ps.SlackBuild
@@ -22,19 +22,30 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# 20260523 bkw: BUILD=4
+# - update to Debian's latest set of patches, which fix a lot of
+#   bugs, including:
+# - fix POSIX::tmpnam() error at runtime. makes html2ps actually *work*;
+#   it hasn't since 15.0 released!
+# - actually include xhtml2ps docs in package.
+# - remove baked-in $PKG path in .ps doc.
+# - add missing "set -e".
+# - fix xhtml2ps view command (gs, not ghostscript).
+# Note that the "Check HTML" xhtml2ps option still doesn't work
+# due to not having "weblint" in Slackware or SBo.
+# This remains Robby's build, but he's too busy to update it
+# at the moment.
+
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=html2ps
 VERSION=${VERSION:-1.0b7}
-BUILD=${BUILD:-3}
+BUILD=${BUILD:-4}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
 ARCH=noarch
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -44,14 +55,7 @@ TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-# We'll default to "letter"
-PAPER=${PAPER:-letter}
-
-# Paper type choices are:
-#   A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10,
-#   B0, B1, B2, B3, B4, B5, B6, B7, B8, B9, B10,
-#   letter, legal, arche, archd, archc, archb, archa,
-#   flsa, flse, halfletter, 11x17, ledger, other
+set -e
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -60,11 +64,27 @@ rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/${PRGNAM}_${VERSION}.orig.tar.gz
 cd $PRGNAM-$VERSION
 chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
- -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
- -exec chmod 644 {} \;
+find . ! -type l    -a \
+  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
+  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \)
+
+# 20260523 bkw: For a long time now, this would build but fail
+# at run time. These patches from Debian fix it, along with some
+# other issues.
+for i in $( cat $CWD/patches/series ); do
+  patch -p1 < $CWD/patches/$i
+done
+
+# 20260523 bkw: We don't have Debian's "see" command, so:
+sed -i 's,"see","gv",' contrib/xhtml2ps/xhtml2ps
+
+# 20260523 bkw: One more patch, written by me, to make the window's
+# close button work. Without this, xhtml2ps's window disappears when
+# you close it, but the process keeps running. Ugh.
+patch -p1 < $CWD/close_button.diff
+
+PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
+PKGXDOC=$PKGDOC/xhtml2ps
 
 # Create the skeleton directory
 mkdir -p \
@@ -72,10 +92,7 @@ mkdir -p \
   $PKG/usr/man/man1 \
   $PKG/usr/man/man5 \
   $PKG/usr/share/html2ps \
-  $PKG/usr/doc/$PRGNAM-$VERSION
-
-# get rid of 'Use of assignment to $[ is deprecated' warning
-patch -p1 < $CWD/no_deprecated_assignment.diff
+  $PKGXDOC
 
 # hardcode the answers to all the questions it wants to ask
 patch -p1 < $CWD/noninteractive_install.diff
@@ -91,16 +108,16 @@ cp -a contrib/xhtml2ps/xhtml2ps $PKG/usr/bin
 cat $CWD/xhtml2ps.desktop > $PKG/usr/share/applications/xhtml2ps.desktop
 cat $CWD/xhtml2ps.png > $PKG/usr/share/pixmaps/xhtml2ps.png
 
+cp -a COPYING README html2ps.ps $PKGDOC
+cp -a contrib/xhtml2ps/LICENSE $PKGXDOC
+cp -a contrib/xhtml2ps/README $PKGXDOC
+cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild
+
 # Now filter out the "$PKG" strings:
 sed -i "s,$PKG,,g" $(find $PKG -type f -print)
 
-find $PKG/usr/man -type f -exec gzip -9 {} \;
-
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/xhtml2ps/
-cp -a COPYING README html2ps.ps $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a contrib/xhtml2ps/LICENSE $PKG/usr/doc/$PRGNAM-$VERSION/LICENSE.xhtml2ps
-cp -a contrib/xhtml2ps/README $PKG/usr/doc/$PRGNAM-$VERSION/README.xhtml2ps
-cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+# 20260523 bkw: do this after $PKG-removal.
+gzip -9 $PKG/usr/man/man*/*
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
