games/dealers-choice: Updated for version 0.0.14                       Removed python3-meson-opt references                       (no longer required)
Signed-off-by: Christoph Willing <chris.willing@slackbuilds.org>

Signed-off-by: Willy Sudiarto Raharjo <willysr@slackbuilds.org>

diff --git a/games/dealers-choice/dealers-choice.SlackBuild b/games/dealers-choice/dealers-choice.SlackBuild
--- a/games/dealers-choice/dealers-choice.SlackBuild
+++ b/games/dealers-choice/dealers-choice.SlackBuild
@@ -25,10 +25,12 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=dealers-choice
-VERSION=${VERSION:-0.0.13}
+VERSION=${VERSION:-0.0.14}
+SOURCEARCHIVE=$PRGNAM-$VERSION.tar.xz
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
+TEST=${TEST:-no}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -65,12 +67,12 @@ cd $TMP
 rm -rf $PRGNAM-$VERSION
 
 # Read the .info and make sure the md5sum matches.
-if ! echo "$(grep '^MD5SUM=' $CWD/$PRGNAM.info | cut -d'"' -f2)  $CWD/$PRGNAM-$VERSION.tar.xz" | md5sum -c - ; then
-  echo "ERROR: MD5 checksum mismatch for $PRGNAM-$VERSION.tar.xz" >&2
+if ! echo "$(grep '^MD5SUM=' $CWD/$PRGNAM.info | cut -d'"' -f2)  $CWD/$SOURCEARCHIVE" | md5sum -c - ; then
+  echo "ERROR: MD5 checksum mismatch for $SOURCEARCHIVE" >&2
   exit 1
 fi
 
-tar xvf $CWD/$PRGNAM-$VERSION.tar.xz
+tar xvf $CWD/$SOURCEARCHIVE
 cd $PRGNAM-$VERSION
 chown -R root:root .
 find -L . \
@@ -91,13 +93,18 @@ cd build
   meson setup .. \
     --buildtype=release \
     -Dstrip=true \
-    -Db_sanitize=none \
     -Db_lto=true \
     --prefix=/usr \
     --localedir=/usr/share/locale \
     -Ddocdir=/usr/doc/$PRGNAM-$VERSION
-  ninja
-  DESTDIR=$PKG ninja install
+  meson compile
+  meson install --destdir $PKG
+  # Opt-in test run (TEST=yes). --setup One_pass runs each looping test a
+  # single time; results are saved into the package's doc dir.
+  if [ "$TEST" = "yes" ]; then
+    meson test --setup One_pass | tee \
+      $PKG/usr/doc/$PRGNAM-$VERSION/test_results.txt
+  fi
 cd ..
 
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
